name: CPDaily_Submit

on:
  watch:
    type: started

#   schedule:
#     - cron: '0 2 * * *'

jobs:
  Submit:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Submit
      run: |
        sudo apt-get install tesseract-ocr
        java -jar Cpdaily_Submit.jar ${{secrets.ID}} ${{secrets.PW}} ${{secrets.ADDRESS}} ${{secrets.KEYS}} ${{secrets.FROM_MAIL}} ${{secrets.FROM_MAIL_PWD}} ${{secrets.TO_MAIL}}
